<!DOCTYPE html>
<html>
    <head>
        <title>Ng2 Test</title>
        <meta charset="utf-8" />
        <base href="<?php echo BASE_URI_PATH . '/' ?>">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/shim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.6.12/zone.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/reflect-metadata/0.1.4/Reflect.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.36/system.js"></script>

        <script src="ng2/systemjs.config.js"></script>
        <script src="ng2/app/main.js"></script>
        <script>
            System.import('bootstrap').catch(function(err){ console.error(err); });
        </script>
    </head>
    <body>
        <ng-app>Loading...</ng-app>
    </body>
</html>