<!DOCTYPE html>
<html>
    <head>
        <title>Ng2 Test</title>
        <meta charset="utf-8" />
        
        <script src="ng2/vendor/core-js/client/shim.min.js"></script>
        <script src="ng2/vendor/zone.js/dist/zone.js"></script>
        <script src="ng2/vendor/reflect-metadata/Reflect.js"></script>
        <script src="ng2/vendor/systemjs/dist/system.src.js"></script>

        <script src="ng2/systemjs.config.js"></script>
        <script src="ng2/app/main.js"></script>
        <script>
            System.import('bootstrap').catch(function(err){ console.error(err); });
        </script>
    </head>
    <body>
        <ng-app>Loading...</ng-app>
    </body>
</html>